services:
  app:
    build: .
    ports:
      - "127.0.0.1:8000:8000"  # Only localhost access
    environment:
      - DATABASE_URL=postgresql+asyncpg://newsuser:newspass@db:5432/newsdigest
      - REDIS_URL=redis://redis:6379
      - LM_STUDIO_URL=http://host.docker.internal:1234/v1
    depends_on:
      - db
      - redis
    volumes:
      - ./config:/app/config:ro  # Read-only config
    restart: unless-stopped
    
    # 🔒 SECURITY: Moderate hardening (keeps network functionality)
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_RAW      # For network access
      - NET_BIND_SERVICE  # For binding ports
    user: "1000:1000"
    
    # Writable areas via tmpfs (for scrapers that need temp files)
    tmpfs:
      - /tmp:exec,nosuid,nodev,size=100m
      - /app/logs:exec,nosuid,nodev,size=50m
      - /home/newsapp/.local:noexec,nosuid,nodev,size=50m

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: newsuser
      POSTGRES_PASSWORD: newspass
      POSTGRES_DB: newsdigest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "127.0.0.1:8081:8081"
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
